### ISSUE TITLE
Create a .csv upload

### ISSUE THREAD

**Issue by grossosavoy** [lohriialo/indesign-server-python#1]
Hi Lohrii,

i am currently trying to work on a webapp that allows me to upload a .csv file and import the Data into an Indesign Template.
Now my questions are:
Is this even possible?
If yes, where do i start?

I am totally new to Indesign Server and it is quit hard to find material for beginners. I stumbled over your repo and thought i would give it a shot. It would be great if you can help me. 

Thanks a lot,

Danny

**Comment by lohriialo** [comment]
It should be possible with data merge in InDesign, I'd suggest reading how data merge works in InDesign https://helpx.adobe.com/indesign/user-guide.html/si/indesign/using/data-merge.ug.html

You can then use scripting to do the data merge, here's some quick google search examples for reference :  
- https://graphicdesign.stackexchange.com/questions/29474/data-merge-exports-to-multiple-pdfs-all-uniquely-named-from-data
- https://gist.github.com/brysonian/4339349

If you're sending some simple data, you could also use script labels which is easier to get started, example : 
- https://github.com/lohriialo/indesign-server-python#example

**Comment by grossosavoy** [comment]
First of all thank you very much for your help.

This would basically mean that Indesign Server is not needed right?
Is it possible to create an interface where you simply upload the .csv file and then it spits out the finished PDF?

Thanks again :)

**Comment by lohriialo** [comment]
InDesign Server context is required for all script execution

**Comment by grossosavoy** [comment]
Thanks for your help!
